name: Segundo Workflow

on:
  push:

jobs:
  segundo-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Segundo passo"
      - name: Checkout
        uses: actions/checkout@v5
      - name: Lista arquivos
        run: ls ${{ github.workspace }}
      - name: Data e hora da execução
        run: date
      - name: Sistema operacional do runner
        run: uname -a
      - name: Versão do Git
        run: git --version
      - name: Conteúdo do README.md
        run: cat README.md
      - name: Lista arquivos novamente
        run: ls ${{ github.workspace }}
      - name: Status
        run: echo "Status ${{ job.status }}."