name: Terceiro Workflow

on:
  push:

env:
  CURSO: Integração Contínua

jobs:
  terceiro-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Terceiro passo"
      - name: Checkout
        uses: actions/checkout@v5
      - name: Lista arquivos
        run: ls ${{ github.workspace }}
      - name: Data e hora da execução
        run: date
      - name: Sistema operacional do runner
        run: uname -a
      - name: Versão do Git
        run: git --version
      - name: Conteúdo do README.md
        run: cat README.md
      - name: Lista arquivos novamente
        run: ls ${{ github.workspace }}
      - name: Exibe variáveis
        run: echo "Nome do curso ${{ env.CURSO }}"
             echo "Usuário ${{ github.actor }}"
             echo "RepositóriO ${{ github.repository }}"
      - name: Status
        run: echo "Status ${{ job.status }}."